/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.kroegerama.petstore.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * An order for a pets from the pet store
 * @param id 
 * @param petId 
 * @param quantity 
 * @param shipDate 
 * @param status Order Status
 * @param complete 
 */
@JsonClass(generateAdapter = true)
data class Order (
    @Json(name = "id") val id: kotlin.Long? = null,

    @Json(name = "petId") val petId: kotlin.Long? = null,

    @Json(name = "quantity") val quantity: kotlin.Int? = null,

    @Json(name = "shipDate") val shipDate: kotlin.String? = null,

    @Json(name = "status") val status: Order.Status? = null,

    @Json(name = "complete") val complete: kotlin.Boolean? = false
) {

    /**
    * Order Status
    * Values: placed,approved,delivered
    */
    enum class Status(val value: kotlin.String){
    
        @Json(name = "placed")
        Placed("placed"),
    
        @Json(name = "approved")
        Approved("approved"),
    
        @Json(name = "delivered")
        Delivered("delivered");
    
    }

}

