/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
*
* The version of the OpenAPI document: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.kroegerama.petstore.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A User who is purchasing from the pet store
 * @param id 
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param password 
 * @param phone 
 * @param userStatus User Status
 */
@JsonClass(generateAdapter = true)
data class User (
    @Json(name = "id") val id: kotlin.Long? = null,

    @Json(name = "username") val username: kotlin.String? = null,

    @Json(name = "firstName") val firstName: kotlin.String? = null,

    @Json(name = "lastName") val lastName: kotlin.String? = null,

    @Json(name = "email") val email: kotlin.String? = null,

    @Json(name = "password") val password: kotlin.String? = null,

    @Json(name = "phone") val phone: kotlin.String? = null,

    @Json(name = "userStatus") val userStatus: kotlin.Int? = null
)

